### ISSUE TITLE
crate update problem

### ISSUE THREAD

**Issue by HyeokSuLee** [blaind/ttf2mesh-rs#3]
cl.exe error again. 
I've found that crates system doesn't update ttf2mesh-sys. 
Maybe it is same version as 0.0.1.
Could you separate it as independent crate or update the version 0.0.2?

**Comment by blaind** [comment]
Thanks for the note.

Published ttf2mesh v0.0.11 and also ttf2mesh with v0.0.2

Seems like from semver point of view, next step would be to go into 0.1.x where the dependency minor updates should be automatic (doesn't happen in 0.0.x yet).
